### ISSUE TITLE
how to add tinyshell webshells?

### ISSUE THREAD

**Issue by 0xh4di** [cybersecmoo/brownie-tub#43]
I want to manage tinyshell webshell using brownie-tub, but really confused about how to this! any help?

**Comment by cybersecmoo** [comment]
Not used tinyshell myself, but from what I can gather, you can use it to generate shells in different languages, and it handles shell commands slightly differently than what Brownie tub expects. 

You see, brownie tub expects the password field and the actual command field to be separate. For example, password being stored in a Cookie called "Authorization", and the command itself being stored in a GET parameter of some sort. 

Tinyshell, on the other hand, appears to generate shells which expect the password to be *name* of the field, with the command being the *value*. For example, a Cookie called `password`, with a value of `whoami`. 

So using the standard Brownie tub Password options would not work so well. HOWEVER! You can make it work. To do so, you'll need to set the Command parameter Name to <whatever the password is>.

Example to follow.

**Comment by cybersecmoo** [comment]
Say you generate a shell by running:
`python tinyshell.py --url=http://www.server.com/index.php --language=php --password=token --mode=base64_post`

This will create a shell that expects to be passed something like `token:whoami` within its POST data.

To model this in Bronie-Tub, you need to create a shell (using the + button on the left), and set the Command Param Type (the dropdown) to POST, set the encoding type to Base64 (since the tinyshell command we ran told it to use base64), and set the Param Name to `token` (i.e. the password).

From there, you should be able to use brownie-tub as normal, except the details column on the right will look a bit weird since it doesn't know you're using a password).

Let me know how this works out for you, and I'll have a think about whether I can modify the application to support tinyshell shells without having to do this workaround.

**Comment by 0xh4di** [comment]
Thanks for your reply.
No chance. I follow the steps but I didn't receive any response from server. try on both aspx and php, but nothing happened.
how can I set proxy on brownie tub? I can monitor request with burp so can debug what's wrong on parameters.

**Comment by cybersecmoo** [comment]
Hm, that is interesting. Tell you what, I'll pop an issue up for this (and proxy-awareness, though it is possible that it might work if you just set the `HTTP_PROXY`/`HTTPS_PROXY` env variables) and I'll install tinyshell on my end and see what's what.

Thanks for bringing this to my attention :)
